### ISSUE TITLE
romfontr corrupts ROM header if -u parameter is used

### ISSUE THREAD

**Issue by brunobox99** [agroza/romfontr#1] opened 2021-02-12 00:25 UTC
romfontr works OK for inserting a new font to a VGA ROM, but if I use the -u parameter (Update 8-Bit Checksum), it writes "00" at the start of the ROM, corrupting the header. It does not write a checksum at the end of the file, as it should.

**Comment by agroza** [comment] 2021-02-12 07:45
Hi brunobox99,

Thank you for opening this issue. I will look into it in a couple of days and try to fix it.
Can you please give me more information, like the exact commandline parameters you have used so that I could try replicating the issue?
I am very curious for more details as well: what BIOS are you modifying and how have you generated the replacement fonts binary file.

PS: I have also updated the broken link ([Microelectronics - VGA ROM Fonts Essay](http://www.alexandrugroza.ro/microelectronics/essays-research/vga-rom-fonts/index.html)) in the README.MD file in the main page where I was describing the ROM Fonts changing procedure in depth.

Thanks,

**Comment by brunobox99** [comment] 2021-02-12 18:23
romfontr.zip
<https://drive.google.com/file/d/1RYupDJJUZakxD3-12WfJMll8MdTpGeMM/view?usp=drive_web>

Hello Alexandru, sorry for the late reply.

I am attaching (in my Google Drive) a zip file with romfontr + font files +
my original unpatched video rom + a batch file that automates the process.

The problem is that if I use the -u parameter in romfontr, it writes a zero
"0" at the start of the rom in the header, instead of fixing the checksum
in the last byte of the file.

Please let me know if I can help with something.

Thanks,

Bruno

**Comment by agroza** [comment] 2021-02-14 19:38
Thank you for the details.
Unfortunately I don't have access to the romfontr.zip link you sent me. Google Drive says I'm not allowed to download it.
I have just requested access to it directly on Drive.

**Comment by brunobox99** [comment] 2021-02-15 15:05
Hello Alexandru, sorry for the delay. Please try now.

**Comment by agroza** [comment] 2021-02-15 16:09
Hi,

Thank you for the access.
I have downloaded the file, analyzed the contents and found the issue.
I will try to fix it in the next couple of days. I will keep you updated.

Alex

**Comment by agroza** [comment] 2021-02-16 20:30
Hi,

I have implemented a fix for the issue and updated both the binary output file which you can use directly, and the source code.
I did some tests and it appears that the issue is now fixed.
But please test for yourself and come back with a reply whether it works as expected or not.

Thanks,
Alex

**Comment by agroza** [comment] 2021-02-23 12:39
Hi Bruno,

I just wanted to know if you had time to verify and validate the fix, so that I can close this issue.

Thanks,

**Comment by brunobox99** [comment] 2021-02-23 16:00
Good day Alexandru, please excuse me for taking so long to reply. I will
test the changes tonight and get back to you ASAP.

Thank you,

Bruno

**Comment by brunobox99** [comment] 2021-02-24 01:53
Thanks Alexandru, the bug with big ROM files is fixed now.

**Closed as completed** 2021-02-24 01:53 UTC
